[alembic]
<<<<<<< HEAD
script_location = %(here)s/alembic
sqlalchemy.url = postgresql+psycopg://user:pass@localhost:5432/dbname
=======
script_location = alembic
prepend_sys_path = .
sqlalchemy.url = driver://user:pass@localhost/dbname
>>>>>>> database-implementation-2

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
<<<<<<< HEAD
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
=======
level = INFO
handlers = console

[logger_sqlalchemy]
level = WARN
handlers = console
>>>>>>> database-implementation-2
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[handler_console]
class = StreamHandler
<<<<<<< HEAD
level = INFO
formatter = generic
args = (sys.stdout,)

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
=======
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
>>>>>>> database-implementation-2
