"""add identity defaults to bigint primary keys

Revision ID: f1e2d3c4b5a6
Revises: 8e1ca8ea1e57
Create Date: 2026-03-23 20:10:00.000000
"""

from __future__ import annotations

from alembic import op

# revision identifiers, used by Alembic.
revision = "f1e2d3c4b5a6"
down_revision = "8e1ca8ea1e57"
branch_labels = None
depends_on = None


TABLES_WITH_BIGINT_PK = (
    "users",
    "data_providers",
    "city_points",
    "households",
    "user_preferences",
    "household_members",
    "external_stations",
    "location_station_cache",
    "provider_cache_entries",
    "geocode_cache_entries",
    "ingest_runs",
    "user_sessions",
    "user_qingping_integrations",
    "indoor_sensor_readings",
    "feedback",
)


def _add_identity_and_sync_sequence(table_name: str) -> None:
    op.execute(
        f"""
        DO $$
        DECLARE
            seq_name text;
            has_identity text;
            has_default text;
            start_with bigint;
        BEGIN
            SELECT c.is_identity, c.column_default
            INTO has_identity, has_default
            FROM information_schema.columns c
            WHERE c.table_schema = current_schema()
              AND c.table_name = '{table_name}'
              AND c.column_name = 'id';

            IF has_identity IS DISTINCT FROM 'YES' AND has_default IS NULL THEN
                EXECUTE 'ALTER TABLE {table_name} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
            END IF;

            SELECT pg_get_serial_sequence('{table_name}', 'id') INTO seq_name;
            SELECT COALESCE(MAX(id), 0) + 1 INTO start_with FROM {table_name};

            IF seq_name IS NOT NULL THEN
                EXECUTE format('SELECT setval(%L, %s, false)', seq_name, start_with);
            END IF;
        END
        $$;
        """
    )


def upgrade() -> None:
    for table_name in TABLES_WITH_BIGINT_PK:
        _add_identity_and_sync_sequence(table_name)


def downgrade() -> None:
    for table_name in TABLES_WITH_BIGINT_PK:
        op.execute(
            f"ALTER TABLE {table_name} ALTER COLUMN id DROP IDENTITY IF EXISTS"
        )
