"""add saved_locations table

Revision ID: g2h3i4j5k6l7
Revises: f1e2d3c4b5a6
Create Date: 2026-03-24 00:00:00.000000
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "g2h3i4j5k6l7"
down_revision = "f1e2d3c4b5a6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "saved_locations",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("label", sa.String(255), nullable=False),
        sa.Column("lat", sa.Numeric(9, 6), nullable=False),
        sa.Column("lon", sa.Numeric(9, 6), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_saved_locations_user_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_saved_locations"),
        sa.UniqueConstraint(
            "user_id", "label", name="uq_saved_locations_user_label"
        ),
        sa.CheckConstraint(
            "lat BETWEEN -90 AND 90", name="ck_saved_locations_lat_range"
        ),
        sa.CheckConstraint(
            "lon BETWEEN -180 AND 180", name="ck_saved_locations_lon_range"
        ),
    )
    op.create_index(
        "ix_saved_locations_user_id", "saved_locations", ["user_id"], unique=False
    )
    op.execute(
        """
        DO $$
        DECLARE
            seq_name text;
            has_identity text;
            has_default text;
            start_with bigint;
        BEGIN
            SELECT c.is_identity, c.column_default
            INTO has_identity, has_default
            FROM information_schema.columns c
            WHERE c.table_schema = current_schema()
              AND c.table_name = 'saved_locations'
              AND c.column_name = 'id';

            IF has_identity IS DISTINCT FROM 'YES' AND has_default IS NULL THEN
                EXECUTE 'ALTER TABLE saved_locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
            END IF;

            SELECT pg_get_serial_sequence('saved_locations', 'id') INTO seq_name;
            SELECT COALESCE(MAX(id), 0) + 1 INTO start_with FROM saved_locations;

            IF seq_name IS NOT NULL THEN
                EXECUTE format('SELECT setval(%L, %s, false)', seq_name, start_with);
            END IF;
        END
        $$;
        """
    )


def downgrade() -> None:
    op.drop_index("ix_saved_locations_user_id", table_name="saved_locations")
    op.drop_table("saved_locations")
