"""add garmin_training_activities table

Revision ID: h4i5j6k7l8m9
Revises: g2h3i4j5k6l7
Create Date: 2026-03-29 00:00:00.000000
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "h4i5j6k7l8m9"
down_revision = "2f6e7d8c9b0a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "garmin_training_activities",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("provider", sa.String(length=32), server_default="garmin", nullable=False),
        sa.Column("activity_id", sa.BigInteger(), nullable=False),
        sa.Column("external_uuid", sa.String(length=255), nullable=True),
        sa.Column("source_file_name", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("activity_type", sa.String(length=64), nullable=True),
        sa.Column("sport_type", sa.String(length=64), nullable=True),
        sa.Column("location_name", sa.String(length=255), nullable=True),
        sa.Column("start_time_gmt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("start_time_local", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_minutes", sa.Numeric(10, 2), nullable=True),
        sa.Column("elapsed_duration_minutes", sa.Numeric(10, 2), nullable=True),
        sa.Column("moving_duration_minutes", sa.Numeric(10, 2), nullable=True),
        sa.Column("calories", sa.Numeric(10, 2), nullable=True),
        sa.Column("average_heart_rate", sa.Numeric(8, 2), nullable=True),
        sa.Column("max_heart_rate", sa.Numeric(8, 2), nullable=True),
        sa.Column("min_heart_rate", sa.Numeric(8, 2), nullable=True),
        sa.Column("distance_km", sa.Numeric(10, 2), nullable=True),
        sa.Column("raw_payload_json", sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_garmin_training_activities_user_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_garmin_training_activities"),
        sa.UniqueConstraint(
            "user_id",
            "activity_id",
            name="uq_garmin_training_activities_user_activity",
        ),
    )
    op.create_index(
        "ix_garmin_training_activities_user_id",
        "garmin_training_activities",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_garmin_training_activities_start_time_gmt",
        "garmin_training_activities",
        ["start_time_gmt"],
        unique=False,
    )
    op.execute(
        """
        DO $$
        DECLARE
            seq_name text;
            has_identity text;
            has_default text;
            start_with bigint;
        BEGIN
            SELECT c.is_identity, c.column_default
            INTO has_identity, has_default
            FROM information_schema.columns c
            WHERE c.table_schema = current_schema()
              AND c.table_name = 'garmin_training_activities'
              AND c.column_name = 'id';

            IF has_identity IS DISTINCT FROM 'YES' AND has_default IS NULL THEN
                EXECUTE 'ALTER TABLE garmin_training_activities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
            END IF;

            SELECT pg_get_serial_sequence('garmin_training_activities', 'id') INTO seq_name;
            SELECT COALESCE(MAX(id), 0) + 1 INTO start_with FROM garmin_training_activities;

            IF seq_name IS NOT NULL THEN
                EXECUTE format('SELECT setval(%L, %s, false)', seq_name, start_with);
            END IF;
        END
        $$;
        """
    )


def downgrade() -> None:
    op.drop_index("ix_garmin_training_activities_start_time_gmt", table_name="garmin_training_activities")
    op.drop_index("ix_garmin_training_activities_user_id", table_name="garmin_training_activities")
    op.drop_table("garmin_training_activities")
