"""add suggestion_feedback table

Revision ID: j1k2l3m4n5o6
Revises: h4i5j6k7l8m9
Create Date: 2026-03-29 00:30:00.000000
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "j1k2l3m4n5o6"
down_revision = "h4i5j6k7l8m9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "suggestion_feedback",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("vote", sa.String(length=20), nullable=False),
        sa.Column("suggestion_id", sa.String(length=120), nullable=False),
        sa.Column("suggestion_family", sa.String(length=80), nullable=True),
        sa.Column("suggestion_category", sa.String(length=80), nullable=True),
        sa.Column("suggestion_title", sa.String(length=255), nullable=True),
        sa.Column("suggestion_short_label", sa.String(length=120), nullable=True),
        sa.Column("suggestion_recommendation", sa.Text(), nullable=True),
        sa.Column("suggestion_impact", sa.Text(), nullable=True),
        sa.Column("location_label", sa.String(length=255), nullable=True),
        sa.Column("lat", sa.Numeric(9, 6), nullable=True),
        sa.Column("lon", sa.Numeric(9, 6), nullable=True),
        sa.Column("source_view", sa.String(length=80), nullable=True),
        sa.Column("suggestion_payload_json", sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("context_payload_json", sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("settings_payload_json", sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_reviewed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_suggestion_feedback_user_id", ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name="pk_suggestion_feedback"),
    )
    op.create_index("ix_suggestion_feedback_user_id", "suggestion_feedback", ["user_id"], unique=False)
    op.create_index("ix_suggestion_feedback_created_at", "suggestion_feedback", ["created_at"], unique=False)
    op.create_index("ix_suggestion_feedback_vote", "suggestion_feedback", ["vote"], unique=False)
    op.execute(
        """
        DO $$
        DECLARE
            seq_name text;
            has_identity text;
            has_default text;
            start_with bigint;
        BEGIN
            SELECT c.is_identity, c.column_default
            INTO has_identity, has_default
            FROM information_schema.columns c
            WHERE c.table_schema = current_schema()
              AND c.table_name = 'suggestion_feedback'
              AND c.column_name = 'id';

            IF has_identity IS DISTINCT FROM 'YES' AND has_default IS NULL THEN
                EXECUTE 'ALTER TABLE suggestion_feedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
            END IF;

            SELECT pg_get_serial_sequence('suggestion_feedback', 'id') INTO seq_name;
            SELECT COALESCE(MAX(id), 0) + 1 INTO start_with FROM suggestion_feedback;

            IF seq_name IS NOT NULL THEN
                EXECUTE format('SELECT setval(%L, %s, false)', seq_name, start_with);
            END IF;
        END
        $$;
        """
    )


def downgrade() -> None:
    op.drop_index("ix_suggestion_feedback_vote", table_name="suggestion_feedback")
    op.drop_index("ix_suggestion_feedback_created_at", table_name="suggestion_feedback")
    op.drop_index("ix_suggestion_feedback_user_id", table_name="suggestion_feedback")
    op.drop_table("suggestion_feedback")
