"""add strava integrations and provider-aware training uniqueness

Revision ID: s1t2r3a4v5a6
Revises: r2s3t4u5v6w7
Create Date: 2026-04-13 00:00:00.000000
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "s1t2r3a4v5a6"
down_revision = "r2s3t4u5v6w7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "user_strava_integrations",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("provider", sa.String(length=32), server_default="strava", nullable=False),
        sa.Column("athlete_id", sa.BigInteger(), nullable=True),
        sa.Column("athlete_username", sa.String(length=255), nullable=True),
        sa.Column("athlete_name", sa.String(length=255), nullable=True),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=False),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="connected", nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_user_strava_integrations_user_id", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name="pk_user_strava_integrations"),
        sa.UniqueConstraint("user_id", name="uq_user_strava_integrations_user_id"),
    )
    op.create_index(
        "ix_user_strava_integrations_user_id",
        "user_strava_integrations",
        ["user_id"],
        unique=False,
    )
    op.execute(
        """
        DO $$
        DECLARE
            seq_name text;
            has_identity text;
            has_default text;
            start_with bigint;
        BEGIN
            SELECT c.is_identity, c.column_default
            INTO has_identity, has_default
            FROM information_schema.columns c
            WHERE c.table_schema = current_schema()
              AND c.table_name = 'user_strava_integrations'
              AND c.column_name = 'id';

            IF has_identity IS DISTINCT FROM 'YES' AND has_default IS NULL THEN
                EXECUTE 'ALTER TABLE user_strava_integrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
            END IF;

            SELECT pg_get_serial_sequence('user_strava_integrations', 'id') INTO seq_name;
            SELECT COALESCE(MAX(id), 0) + 1 INTO start_with FROM user_strava_integrations;

            IF seq_name IS NOT NULL THEN
                EXECUTE format('SELECT setval(%L, %s, false)', seq_name, start_with);
            END IF;
        END
        $$;
        """
    )

    op.drop_constraint(
        "uq_garmin_training_activities_user_activity",
        "garmin_training_activities",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_garmin_training_activities_user_provider_activity",
        "garmin_training_activities",
        ["user_id", "provider", "activity_id"],
    )


def downgrade() -> None:
    op.drop_constraint(
        "uq_garmin_training_activities_user_provider_activity",
        "garmin_training_activities",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_garmin_training_activities_user_activity",
        "garmin_training_activities",
        ["user_id", "activity_id"],
    )
    op.drop_index("ix_user_strava_integrations_user_id", table_name="user_strava_integrations")
    op.drop_table("user_strava_integrations")
